### ISSUE TITLE
local build is failing for linux_aarch64_USE_OPENM0/1 build configs

### ISSUE THREAD

**Issue by snadampal** [conda-forge/openblas-feedstock#157]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I was trying to build openblas conda package aarch64 linux platform using `build-locally.py` script and it was failing because the build configs (5 and 6, linux_aarch64_USE_OPENMP0 and 1) are using the x86 docker images.

**How to reproduce?**

```
git clone https://github.com/conda-forge/openblas-feedstock.git
cd openblas-feedstock
python3 build-locally.py linux_aarch64_USE_OPENMP1 (or python3 build-locally.py linux_aarch64_USE_OPENMP0)


```
**Error**
```
++ cat /home/ubuntu/openblas-feedstock-sn/openblas-feedstock/.ci_support/linux_aarch64_USE_OPENMP1.yaml
++ shyaml get-value docker_image.0 quay.io/condaforge/linux-anvil-comp7
+ DOCKER_IMAGE=quay.io/condaforge/linux-anvil-cos7-x86_64
+ mkdir -p /home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build_artifacts
+ DONE_CANARY=/home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build_artifacts/conda-forge-build-done-linux_aarch64_USE_OPENMP1
+ rm -f /home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build_artifacts/conda-forge-build-done-linux_aarch64_USE_OPENMP1
+ DOCKER_RUN_ARGS=
+ '[' -z '' ']'
+ DOCKER_RUN_ARGS='-it '
Start Docker
+ export UPLOAD_PACKAGES=False
+ UPLOAD_PACKAGES=False
+ export IS_PR_BUILD=True
+ IS_PR_BUILD=True
+ docker pull quay.io/condaforge/linux-anvil-cos7-x86_64
Using default tag: latest
latest: Pulling from condaforge/linux-anvil-cos7-x86_64
Digest: sha256:f9d074fad02ae7118a7acabf4f1843d10373e3a0427665501bf3a753b67c1cec
Status: Image is up to date for quay.io/condaforge/linux-anvil-cos7-x86_64:latest
quay.io/condaforge/linux-anvil-cos7-x86_64:latest
+ docker run -it -v /home/ubuntu/openblas-feedstock-sn/openblas-feedstock/recipe:/home/conda/recipe_root:rw,z,delegated -v /home/ubuntu/openblas-feedstock-sn/openblas-feedstock:/home/conda/feedstock_root:rw,z,delegated -e CONFIG -e HOST_USER_ID -e UPLOAD_PACKAGES -e IS_PR_BUILD -e GIT_BRANCH -e UPLOAD_ON_BRANCH -e CI -e FEEDSTOCK_NAME -e CPU_COUNT -e BUILD_WITH_CONDA_DEBUG -e BUILD_OUTPUT_ID -e flow_run_id -e remote_url -e sha -e BINSTAR_TOKEN -e FEEDSTOCK_TOKEN -e STAGING_BINSTAR_TOKEN quay.io/condaforge/linux-anvil-cos7-x86_64 bash /home/conda/feedstock_root/.scripts/build_steps.sh
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /opt/conda/bin/tini: exec format error
Traceback (most recent call last):
  File "/home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build-locally.py", line 105, in <module>
    main()
  File "/home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build-locally.py", line 93, in main
    run_docker_build(ns)
  File "/home/ubuntu/openblas-feedstock-sn/openblas-feedstock/build-locally.py", line 29, in run_docker_build
    subprocess.check_call([script])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

### Installed packages

```shell
The issue is for the source build.
```

### Environment info

```shell
active environment : conda-openblas-testing
    active env location : /home/ubuntu/.conda/envs/conda-openblas-testing
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files : /opt/conda/.condarc
                          /home/ubuntu/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=neoverse_n1
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/.conda/envs
                          /opt/conda/envs
               platform : linux-aarch64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Linux/6.2.0-1017-aws ubuntu/22.04.2 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by snadampal** [comment]
exporting `DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64` solves the issue.
